spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      properties:
        request.timeout.ms: 60000  # Tăng timeout lên 60 giây
        default.api.timeout.ms: 60000
server:
  port: 8081
logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: DEBUG